- hosts: cockpit
  gather_facts: true
  become: true #become_user
  tasks:
    - name: To create a template file tem.j2 and transfer some attribs to main file(main.html)
      template:
        src: ./files/main3.html
        dest: /root/main.html
