#SPDX-License-Identifier: MIT-0
---
# tasks file for alpine_java_env
- name: install java runtime environment for the packages
  community.generaral.apk: 
    update_cache: true
    name: 
      - openjdk11-jre
      - zip
      - tar
