- hosts: webservers
  become: true
  gather_facts: no
  tasks:
    - name: To test the shell module of the ansible
      shell: |
        touch /home/ubuntu/file11 \
        && touch /home/ubuntu/file2 \
        && touch /home/ubuntu/file3
