- hosts: debian
  become: true
  gather_facts: true
  tasks:
    - name: creating a new directory
      file:
        path: /opt/nexus
        state: directory
        mode: '0755'
        owner: ansible
        group: ansible
        #recurse: true
