- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: installing a package 
      apt:
        name: 
          - lsb-release
          - ca-certificates
          - openssl
        state: latest
        update_cache: true

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - lsb-release
        - openssl

    - name: Install a package
      apt:
        default_release: ansible/ansible
        name: ansible-core
        update_cache: true
        
