- hosts: webservers
  gather_facts: true
  tasks:
    - name: Download package from apt
      apt:
        update_cache: true
        name: "{{ item }}"
        state: latest
        loop:
          - python-is-python3
          - python3-pip
          - virtualenv
          - git 
          - curl 
    - name: Creating an environment and activating
      shell: |
        virtualenv -p python /home/ubuntu/env
        source /home/ubuntu/env/bin/activate
        cd /home/ubuntu
        # After downloading
        mv /home/ubuntu/everest/ramcov4 /home/ubuntu/
        
        
    - name: Download repo from the github
    - name: moving the 'ramcov4' out to 
    - name: starting the application
      shell:
        python manage.py runserver 0.0.0.0:8000
      notify:
        - Restart django server
  handlers:
    - name: Restart django server
      service:
        name: 
