- hosts: sonarservers
  become: true
  gather_facts: false
  tasks: 
    - name: Install Java Runtime environment
      apt:
        update_cache: true
        name: openjdk-11-jre-headless
    - name: Download SonarQube software
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.2.1.78527.zip
        dest: /opt/
    - name: Extract SonarQube Software
      unarchive:
        src: /opt/sonarqube-10.2.1.78527.zip
        dest: /opt/
        remote_src: yes
    - name: Rename the Sonarqube directory
      shell:
        mv /opt/sonarqube-10.2.1.78527 /opt/sonarqube/
    - name: Create the sonar user
      user:
        name: sonar
        create_home: true
        shell: /bin/bash
        comment: "SonarQube Management Account"
        expires: -1
        password: "{{ 'sonar' | password_hash('sha512','A512') }}"
    - name: Setup Sudo Access for sonar User
      copy:
        dest: /etc/sudoers.d/nexus
        content: 'sonar ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
    - name: Change owner and group and permissions to /opt/sonarqube/
      file:
        path: /opt/sonarqube/
        owner: sonar
        group: sonar
        mode: 0775
        recurse: yes
        state: directory
    - name: creating the Sonarqube service 
      copy:
        dest: /etc/systemd/system/sonar.service
        content: | 
          [Unit]
          Description=SonarQube service
          After=syslog.target network.target

          [Service]
          Type=forking

          ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
          ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop

          User=root
          Group=root
          Restart=always

          [Install]
          WantedBy=multi-user.target
    - name: Starting and optimising the sonar service
      become_user: sonar
      service:
        name: sonar.service
        state: restarted
        enabled: true
