- hosts: webservers
  gather_facts: true
  become: true
  tasks:
  - name: install packages using loops
    apt:
      update_cache: true
      state: latest
      name: 
        - docker.io
        - python-is-python3
        - virtualenv
        - python3-pip 
# Loops should not be used with 'apt' as it is not working as below
# name: '{{ item }}'
#   - docker
#    - ansible
