- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: install a packge based on the distribution
      apt: 
        update_cache: true
        name: mc 
        state: latest
      when: ansible_distribution=='Debian'
