- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: checking the mathematical value
      shell: echo "only on Red Hat 6, derivatives, and later"
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['lsb']['major_release'] | int >= 6
