- hosts: cockpit
  gather_facts: true
  become: true
  tasks: 
    - name: Install Sonarqube and arrange the server to be already for deploy
      block: 
        - name: First Installing a few prerequisites
          apt:
            update_cache: true
            name: 
              - default-jre
        - name: Now, get the package from the official website of the Sonarqube
          get_url: 
            url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.6.0.92116.zip
            dest: /opt/
        - name: Create a group for managing sonarqube app
          group:
            name: sonar
        - name: Create a user for sonarqube inorder to manage Sonarqube application
          user: 
            name: sonar
            create_home: true
            group: sonar
            shell: /bin/bash
        - name: Create a new directory to save Sonarqube files
          file:
            path: /opt/sonarqube
            state: directory
            mode: '0755'
            owner: sonar
            group: sonar
        - name: Now, unarchive all the files
          unarchive: 
            src: /opt/sonarqube-10.6.0.9211.zip
            dest: /opt/
            remote_src: true
        - name: Move all the unarchived files to a different dir
          file:
            src: /opt/sonarqube-10.6.0.9211
            dest: /opt/sonarqube
            remote_src: true
